# Generated by Django 4.0.5 on 2022-07-17 04:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userimage',
            field=models.ImageField(blank=True, default='images/default_icon.png', null=True, upload_to=api.models._user_profile_avator_upload_to),
        ),
    ]
